### ISSUE TITLE
systemctl doesn't exist on Ubuntu, which causes an ugly error message

### ISSUE THREAD

**Issue by oviano** [cubiclesoft/service-manager-src#1]
Essentially you get "command not found" appearing in the output, even though the service is successfully installed by other means.

This is because the "UseSystemD" flag is set (correctly), but on Ubuntu (12.04 at least, and probably later) the command systemctl isn't included.

Below is a trivial patch that makes the failure silent (and consistent with similar code nearby.)

Great application by the way!

https://www.dropbox.com/s/55muqwx84bo4fty/make-systemctl-fail-silently-if-it-doesn%27t-exist.patch?dl=0

**Comment by cubiclesoft** [comment]
Huh.  I missed that one completely.  I just assumed (it's always a bad idea to assume something) that if the main systemd library path existed that 'systemctl' would also be available.  Patch applied.  Thanks.

I'm not sure how the service got registered if the systemctl method failed.  The software dumps the service file in either the systemd path OR init.d but not both.  The rest of the registration options should have also failed unless Ubuntu is checking both locations.

Can you look at your update-rc.d script(s) on your system and see if it references the /lib/systemd/system/ directory somewhere?

**Comment by oviano** [comment]
Hello!

Here is a link to the full update-rc.d script found on my system in /usr/sbin.

It definitely works and starts and stops the service reliably on several machines running 16.04 Lubuntu aswell as 12.04 Lubuntu so that fact that it  isn't finding systemctl obviously isn't critical.

Let me know if you need anything else, although I’m off out in a minute so it’ll likely have to wait until tomorrow.

Regards

Oliver

https://www.dropbox.com/s/3wsp2ctfcibqy8v/update-rc.d?dl=0 <https://www.dropbox.com/s/3wsp2ctfcibqy8v/update-rc.d?dl=0>

**Comment by cubiclesoft** [comment]
The update-rc.d script on Ubuntu 12.04 definitely (and probably 14.04 too) checks for the systemd variant:

````
    # In addition to the insserv call we also enable/disable the service
    # for systemd by creating the appropriate symlink in case there is a
    # native systemd service. We need to do this on our own instead of
    # using systemctl because systemd might not even be installed yet.
    my $service_path;
    if (-f "/etc/systemd/system/$scriptname.service") {
        $service_path = "/etc/systemd/system/$scriptname.service";
    } elsif (-f "/lib/systemd/system/$scriptname.service") {
        $service_path = "/lib/systemd/system/$scriptname.service";
    }
````

Well, that solves the only mystery.  Thanks!
